"""Small helpers for loading financial profiles from disk."""

from __future__ import annotations

import json
from pathlib import Path

from engine.models import FinancialProfile

DEFAULT_DATA_PATH = Path(__file__).parent.parent / "data" / "sample_data" / "financial_data.json"


def load_profiles(path: Path | str = DEFAULT_DATA_PATH) -> list[FinancialProfile]:
    """Load all synthetic profiles generated by data/generate_data.py."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"No sample data found at {path}. Run `python data/generate_data.py` first."
        )
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    return [FinancialProfile(**item) for item in raw]


def load_profile_by_id(user_id: str, path: Path | str = DEFAULT_DATA_PATH) -> FinancialProfile:
    profiles = load_profiles(path)
    for p in profiles:
        if p.user_id == user_id:
            return p
    raise ValueError(f"No profile found with user_id={user_id}")


def load_first_profile(path: Path | str = DEFAULT_DATA_PATH) -> FinancialProfile:
    """Convenience helper for demos - just grab the first profile."""
    profiles = load_profiles(path)
    if not profiles:
        raise ValueError("Sample data file is empty.")
    return profiles[0]
